### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/logman#5]
* [x] new API (#6), something like below:
    ```go
    logs := logman.New("path/to/dir")
	err := logs.GC()
	files, err := logs.List()
	err := logs.GCByName("name")
	writer, err := logs.New()
	writer, err := logs.NewWithName("name")
    ```
* [x] add manual GC helpers (full clean etc)
* [ ] support compression
* [ ] support advanced auto-GC rules
* [ ] perform input validation
* [ ] support rotation
* [ ] more tests
* [ ] explain in the readme how the project works
* [ ] add "famous library" integration examples, update the readme, update the project description, post the project on their readme
